### PR TITLE
Images support added.

### PR DESCRIPTION
**Pull request by Gutherz**

### CODE REVIEW

**Comment by abrpatel** [comment]
i made some changes (not elegant, but does the job) to help center the thumb image over the back image.

in the segment control I tweaked this method.
- (void)drawImages {
  int i = 0;
  for (UIImage *image in self.imagesArray) {
  
  ```
  CGRect imageRect = CGRectMake((self.segmentWidth *i), 0, image.size.width, image.size.height);
  
  [image drawInRect:imageRect];
  i++;
  ```
  
  }
  }

and on the segment-thumb, i tweaked this method
- (UIImageView *)imageView {
  
  if (imageView == nil) {
      imageView = [[UIImageView alloc] initWithFrame:CGRectMake(-2, -2, self.bounds.size.width + 4, self.bounds.size.height + 5)];
  
  ```
  [self addSubview:imageView];
  ```
  
  }
  
  return imageView;
  }

Hopefully this will help anyone who isn't getting the balanced effect using the images instead of text.

**Comment by samvermette** [comment]
6 months later, I finally added the implementation I had in mind for image support.

svsegmentedcontrol

You set your section images using `setSectionImages:`. They automatically get tinted using `textColor`. From looking at this pull request, mine seems to be a completely different implementation than what @nivgut had done, but I feel this should be way the way to go.

**Comment by abrpatel** [comment]
*Edit. Actually figured out how to implement it. I actually like your implementation :D

My first app, PlanThirty is something I created for myself to help me track habits. Your control was very useful in its creation, so thank you for sharing it :).  http://tinyurl.com/PlanThirty.

I can gift it to you if you want. Its the least I can do.

**Comment by samvermette** [comment]
@abhim8 looks really great from the screenshots! Would love a promo code, email me hello@samvermette.com

Thank you!

**Pull request closed without merging**
