### PR TITLE
NSArray Properties to Copy Ownership, and Retains/Releases

### PR DESCRIPTION
**Pull request by capnslipp**
Hello,

In using your wonderful SVSegmentedControl library, I noticed a couple of issues.  First, the NSArray properties in the SVSegmentedControl class have strong/retain ownership… generally one wants copy ownership here to avoid issues with the array changing size or its elements at awkward times.

Second, there were some missing retain/releases in some of the custom setters.  I've added those that I spotted on a quick glance.

### CODE REVIEW

**Comment by capnslipp** [comment]
Nevermind; you're using ARC.  I'm not.

It seems the NSArray properties should still have copy semantics in ARC, but I have no idea how to implement this in a setter under ARC.  I'll leave that up to you.

**Comment by samvermette** [comment]
> generally one wants copy ownership here to avoid issues with the array changing size or its elements at awkward times.

Care to elaborate a bit? This sounds sensible but I'm curious to hear about an example use case where not copying `sectionTitles` could go wrong.

**Comment by capnslipp** [comment]
One simple use case would be the count of elements in `sectionTitles` changing when you're using it.

Say the client code hands you an NSMutableArray with 4 elements from a thread that isn't the main thread _(let's say it's a dedicated web request completion thread, since that seems like a type of thing likely to happen)_.  Then, later on you're looping through that same array (since you've only retained it) and the original owner (who still has a reference to it) decides to delete 3 of the 4 elements.

Whoops— your `for(NSString *titleString in self.sectionTitles)` throws a:

```
NSGenericException', reason: '*** Collection <__NSArrayM: 0x7188e90> was mutated while being enumerated.
```

and the whole app crashes.

This issue is nothing new; it's existed from the point in the 1980s when the designers of Obj-C decided to make a number of mutable classes that are subclasses of their non-mutable counterparts.  The counter-balance was to treat mutability as a special-case, and to provide the NSCopying protocol and a custom `copy` implementation on all non-mutable classes _(e.g. `NSArray`)_ that returns a non-mutable shallow copy _(i.e. only a copy of the array's structure; the individual elements are retained the same as if they had been added with `arrayWithObjects:` or `addObject:`)_.  If one really wants a mutable copy, there's the `mutableCopy` method.

It should also be noted that there's no performance penalty for calling `copy` on an immutable object; the implementation of NSArray's (and other immutables') `copy` just retains the object— if it can't be changed, there's no point in copying it (within the scope of normal Obj-C usage, that is).

All of this is covered in somewhere in the Objective-C programming guides that I'm failing to find, in Aaron Hillegass's Cocoa Programming for Mac OS X _(if you have the 2nd edition like me, it's page 125; chapter 6 in the “Starting the RaiseMan Application” section)_, probably in the Hillegass's Cocoa Programming for iOS, and on StackOverflow [here](http://stackoverflow.com/questions/387959/nsstring-property-copy-or-retain), [here](http://stackoverflow.com/questions/14846055/why-is-mutablecopy-here), [here](http://stackoverflow.com/questions/5849942/nsarray-property-copy-or-retain), etc.

I would just fix it and submit a patch back to you… but I'm not terribly familiar with how to do things in ARC.  I suspect it's as simple as setting the property ownership semantics to `copy` and making sure that the initializer and any custom setters call `copy` on the parameter that's passed in and store the return value of the the copy, but I don't know for sure.  However, if you wish I can give it a go; I'm familiar enough with your codebase now.

**Comment by capnslipp** [comment]
P.S. Mid-loop exception test: https://gist.github.com/slippyd/5566398

**Comment by capnslipp** [comment]
Changed my mind: #54 

Passes analyzer and Instruments leak checks, and seems to work.

**Comment by samvermette** [comment]
Thanks for the detailed explanation!

**Comment by capnslipp** [comment]
Of course.  I was refreshing my own understanding as well.

Thank you for the merge!

**Pull request closed without merging**
